# Generated by Django 4.2.6 on 2023-10-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnin', '0007_language_course_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
