# Generated by Django 4.2.6 on 2025-11-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnin', '0015_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
