# Generated by Django 4.2.6 on 2025-11-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnin', '0016_rename_order_id_payment_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment',
            new_name='payment_id',
        ),
    ]
